### ISSUE TITLE
[Tracking] Endpoints to implement

### ISSUE THREAD

**Issue by relrod** [fedora-infra/pagure-haskell#1]
## Projects
- [x] `GET /api/0/<repo>/git/tags`
- [x] `GET /api/0/fork/<username>/<repo>/git/tags`
- [x] `GET /api/0/projects`
## Issues
- [x] `POST /api/0/<repo>/new_issue`
- [x] `POST /api/0/fork/<username>/<repo>/new_issue`
- [x] `GET /api/0/<repo>/issues`
- [x] `GET /api/0/fork/<username>/<repo>/issues`
- [x] `GET /api/0/<repo>/issue/<issue id>`
- [x] `GET /api/0/fork/<username>/<repo>/issue/<issue id>`
- [x] `GET /api/0/<repo>/issue/<issue id>/comment/<comment id>`
- [x] `GET /api/0/fork/<username>/<repo>/issue/<issue id>/comment/<comment id>`
- [x] `POST /api/0/<repo>/issue/<issue id>/comment`
- [x] `POST /api/0/fork/<username>/<repo>/issue/<issue id>/comment`
## Pull Requests
- [ ] `GET /api/0/<repo>/pull-requests`
- [ ] `GET /api/0/fork/<username>/<repo>/pull-requests`
- [x] `GET /api/0/<repo>/pull-request/<request id>`
- [x] `GET /api/0/fork/<username>/<repo>/pull-request/<request id>`
- [x] `POST /api/0/<repo>/pull-request/<request id>/merge`
- [x] `POST /api/0/fork/<username>/<repo>/pull-request/<request id>/merge`
- [x] `POST /api/0/<repo>/pull-request/<request id>/close`
- [x] `POST /api/0/fork/<username>/<repo>/pull-request/<request id>/close`
- [x] `POST /api/0/<repo>/pull-request/<request id>/comment`
- [x] `POST /api/0/fork/<username>/<repo>/pull-request/<request id>/comment`
- [ ] `POST /api/0/<repo>/pull-request/<request id>/flag`
- [ ] `POST /api/0/fork/<username>/<repo>/pull-request/<request id>/flag`
## Users
- [x] `GET /api/0/users`
- [x] `GET /api/0/user/<username>`
- [x] `GET /api/0/groups`
## Extras
- [x] `GET /api/0/version`
- [x] `GET /api/0/error_codes`
- [x] `GET /api/0/<repo>/tags`
- [x] `GET /api/0/fork/<username>/<repo>/tags`

**Comment by relrod** [comment]
Closing this, focusing on rewrite using Servant in `servant` branch.
